Repository skelpo/JWTMiddleware, pull requests merged in 2018-05, with the labels that each got.

#6 Fixed typo in Middleware
  Sources/JWTMiddleware/JWTAuthenticatableMiddleware.swift
  Tests/JWTMiddlewareTests/JWTMiddlewareTests.swift
Labels: typo

#8 Updated Vapor version to official release
  Package.resolved
  Package.swift
Labels: enhancement

#9 Added Model Conformance to JWTAuthenticatable Protocol
  Package.resolved
  Sources/JWTAuthenticatable/JWTAuthenticatable.swift
Labels: bug

#10 RouteRestrictionMiddleware
  README.md
  Sources/JWTMiddleware/AdminMiddleware.swift
Labels: enhancement
